spring:
  application:
    name: restServiceTest
  profiles:
    active: dev
  devtools:
    restart:
      enable: true
  h2:
    console:
      enable: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:

authorizationProfile:
  user: ${USER}
  password: ${PASSWORD}



server:
  port: 8082